CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

-- cliente definição

-- Drop table

-- DROP TABLE cliente;

CREATE TABLE cliente (
	id_cliente int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_cliente varchar NULL,
	cpf varchar NULL,
	CONSTRAINT cliente_pk PRIMARY KEY (id_cliente)
);

-- usuario definição

-- Drop table

-- DROP TABLE usuario;

CREATE TABLE usuario (
	id_usuario int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_usuario varchar NULL,
	nome_empresa varchar NULL,
	email varchar NULL,
	cpf_cnpj varchar NULL,
	rua varchar NULL,
	estado varchar NULL,
	cidade varchar NULL,
	pais varchar NULL,
	telefone varchar NULL,
	cep int4 NULL,
	bairro varchar NULL,
	senha varchar NOT NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id_usuario)
);

ALTER TABLE usuario
ADD COLUMN reset_password_token VARCHAR(255),
ADD COLUMN reset_password_expires TIMESTAMP;

-- estoque definição

-- Drop table

-- DROP TABLE estoque;

CREATE TABLE estoque (
	id_estoque int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descricao varchar NULL,
	id_usuario int4 NULL,
	CONSTRAINT estoque_pk PRIMARY KEY (id_estoque)
);


-- estoque chaves estrangeiras

ALTER TABLE estoque ADD CONSTRAINT estoque_usuario_fk FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;

-- fornecedor definição

-- Drop table

-- DROP TABLE fornecedor;

CREATE TABLE fornecedor (
	id_fornecedor int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo_pessoa varchar NULL,
	documento varchar NULL,
	telefone varchar NULL,
	nome_fornecedor varchar NULL,
	bairro varchar NULL,
	estado varchar NULL,
	cep int4 NULL,
	cidade varchar NULL,
	email varchar NULL,
	pais varchar NULL,
	rua varchar NULL,
	CONSTRAINT fornecedor_pk PRIMARY KEY (id_fornecedor)
);

-- pedido definição

-- Drop table

-- DROP TABLE pedido;

CREATE TABLE pedido (
	id_pedido int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	data_pedido date NULL,
	descricao varchar NULL,
	valor_pedido numeric NULL,
	id_usuario int4 NULL,
	CONSTRAINT pedido_pk PRIMARY KEY (id_pedido)
);


-- pedido chaves estrangeiras

ALTER TABLE pedido ADD CONSTRAINT pedido_usuario_fk FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;

-- produto definição

-- Drop table

-- DROP TABLE produto;

CREATE TABLE produto (
	id_produto int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome_produto varchar NULL,
	categoria varchar NULL,
	peso numeric NULL,
	preco_compra numeric NULL,
	volume numeric NULL,
	descricao varchar NULL,
	lote int4 NULL,
	data_cadastro date NULL,
	preco_venda numeric NULL,
	CONSTRAINT produto_pk PRIMARY KEY (id_produto)
);

-- reposicao definição

-- Drop table

-- DROP TABLE reposicao;

CREATE TABLE reposicao (
	id_reposicao int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	data_reposicao date NULL,
	valor_reposicao varchar NULL,
	id_fornecedor int4 NULL,
	CONSTRAINT reposicao_pk PRIMARY KEY (id_reposicao)
);


-- reposicao chaves estrangeiras

ALTER TABLE reposicao ADD CONSTRAINT reposicao_fornecedor_fk FOREIGN KEY (id_fornecedor) REFERENCES public.fornecedor(id_fornecedor) ON DELETE CASCADE;

-- venda definição

-- Drop table

-- DROP TABLE venda;

CREATE TABLE venda (
	id_venda int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	descricao varchar NULL,
	data_venda date NULL,
	id_usuario int4 NULL,
	valor_venda numeric NULL,
	CONSTRAINT venda_pk PRIMARY KEY (id_venda)
);


-- venda chaves estrangeiras

ALTER TABLE venda ADD CONSTRAINT venda_usuario_fk FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario) ON DELETE CASCADE;




-- contem_produto definição

-- Drop table

-- DROP TABLE contem_produto;

CREATE TABLE contem_produto (
	id_produto int4 NULL,
	id_pedido int4 NULL,
	quantidade_pedido int4 NULL
);


-- contem_produto chaves estrangeiras

ALTER TABLE contem_produto ADD CONSTRAINT contem_produto_pedido_fk FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido) ON DELETE CASCADE;
ALTER TABLE contem_produto ADD CONSTRAINT contem_produto_produto_fk FOREIGN KEY (id_produto) REFERENCES public.produto(id_produto) ON DELETE CASCADE;

-- possui_cliente definição

-- Drop table

-- DROP TABLE possui_cliente;

CREATE TABLE possui_cliente (
	id_cliente int4 NULL,
	id_venda int4 NULL
);


-- possui_cliente chaves estrangeiras

ALTER TABLE possui_cliente ADD CONSTRAINT possui_cliente_cliente_fk FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente) ON DELETE CASCADE;
ALTER TABLE possui_cliente ADD CONSTRAINT possui_cliente_venda_fk FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda) ON DELETE CASCADE;

-- possui_estoque definição

-- Drop table

-- DROP TABLE possui_estoque;

CREATE TABLE possui_estoque (
	id_estoque int4 NULL,
	id_produto int4 NULL,
	quantidade_estoque_total int4 NULL,
	quantidade_estoque_atual int4 NULL
);


-- possui_estoque chaves estrangeiras

ALTER TABLE possui_estoque ADD CONSTRAINT possui_estoque_estoque_fk FOREIGN KEY (id_estoque) REFERENCES public.estoque(id_estoque) ON DELETE CASCADE;
ALTER TABLE possui_estoque ADD CONSTRAINT possui_estoque_produto_fk FOREIGN KEY (id_produto) REFERENCES public.produto(id_produto) ON DELETE CASCADE;

-- possui_reposicao definição

-- Drop table

-- DROP TABLE possui_reposicao;

CREATE TABLE possui_reposicao (
	id_produto int4 NULL,
	id_reposicao int4 NULL,
	quantidade_reposicao int4 NULL
);


-- possui_reposicao chaves estrangeiras

ALTER TABLE possui_reposicao ADD CONSTRAINT possui_reposicao_produto_fk FOREIGN KEY (id_produto) REFERENCES public.produto(id_produto) ON DELETE CASCADE;
ALTER TABLE possui_reposicao ADD CONSTRAINT possui_reposicao_reposicao_fk FOREIGN KEY (id_reposicao) REFERENCES public.reposicao(id_reposicao) ON DELETE CASCADE;

-- possui_venda definição

-- Drop table

-- DROP TABLE possui_venda;

CREATE TABLE possui_venda (
	id_venda int4 NULL,
	id_produto int4 NULL,
	quantidade_venda int4 NULL
);


-- possui_venda chaves estrangeiras

ALTER TABLE possui_venda ADD CONSTRAINT possui_venda_produto_fk FOREIGN KEY (id_produto) REFERENCES public.produto(id_produto) ON DELETE CASCADE;
ALTER TABLE possui_venda ADD CONSTRAINT possui_venda_venda_fk FOREIGN KEY (id_venda) REFERENCES public.venda(id_venda) ON DELETE CASCADE;